export const GET_CLUB_LIST_REQUEST = 'GET_CLUB_LIST_REQUEST';
export const GET_DEPT_LIST_REQUEST = 'GET_DEPT_LIST_REQUEST';
export const GET_CATEGORY_LIST_REQUEST = 'GET_CATEGORY_LIST_REQUEST';
export const GET_CLUB_LIST = 'GET_CLUB_LIST';
export const GET_DEPT_LIST = 'GET_DEPT_LIST';
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST';
