export const GET_DOCUMENT_LIST_REQUEST = 'GET_DOCUMENT_LIST_REQUEST';
export const GET_INFO_POST_REQUEST = 'GET_INFO_POST_REQUEST';
export const GET_MEMBER_LIST_REQUEST = 'GET_MEMBER_LIST_REQUEST';
export const GET_AUTH_LEVEL_REQUEST = 'GET_AUTH_LEVEL_REQUEST';
export const SUBMIT_DOCUMENT_REQUEST = 'SUBMIT_DOCUMENT_REQUEST';
export const SEARCH_DOCUMENT_REQUEST = 'SEARCH_DOCUMENT_REQUEST';
export const CHANGE_AUTH_LEVEL_REQUEST = 'CHANGE_AUTH_LEVEL_REQUEST';
export const GET_DOC_TYPE_LIST_REQUEST = 'GET_DOC_TYPE_LIST_REQUEST';

export const CHANGE_STATUS = 'CHANGE_STATUS';
export const AUTH_CHANGE_MODAL_VISUALIZE = 'AUTH_CHANGE_MODAL_VISUALIZE';
export const REMOVE_MODAL = 'REMOVE_MODAL';

export const UPDATE_DOCUMENT_LIST = 'SET_DOCUMENT_LIST';
export const UPDATE_MEMBER_LIST = 'SET_MEMBER_LIST';
export const UPDATE_INFO_POST = 'SET_INFO_POST';
export const UPDATE_AUTH_LEVEL = 'UPDATE_AUTH_LEVEL';
export const UPDATE_DOC_TYPE_LIST = 'UPDATE_DOC_TYPE_LIST';

export const FINISH_POST = 'FINISH_POST';
export const START_POST = 'START_POST';
