export const GET_DOCUMENT_LIST_REQUEST = 'GET_DOCUMENT_LIST_REQUEST';
export const GET_INFO_POST_REQUEST = 'GET_INFO_POST_REQUEST';
export const GET_MEMBER_LIST_REQUEST = 'GET_MEMBER_LIST_REQUEST';
export const GET_AUTH_LEVEL_REQUEST = 'GET_AUTH_LEVEL_REQUEST';
export const CHANGE_STATUS = 'CHANGE_STATUS';

export const UPDATE_DOCUMENT_LIST = 'SET_DOCUMENT_LIST';
export const UPDATE_MEMBER_LIST = 'SET_MEMBER_LIST';
export const UPDATE_INFO_POST = 'SET_INFO_POST';
