export const REMOVE_DOCUMENT_CATEGORY_SUCCESS = 'REMOVE_DOCUMENT_CATEGORY_SUCCESS';
export const ADD_DOCUMENT_CATEGORY_SUCCESS = 'ADD_DOCUMENT_CATEGORY_SUCCESS';
export const FETCH_CATEGORY_LIST_SUCCESS = 'FETCH_DOC_TYPE_SUCCESS';

export const FETCH_CATEGORY_LIST_REQUEST = 'FETCH_CATEGORY_LIST_REQUEST';
export const REMOVE_DOCUMENT_CATEGORY_REQUEST = 'REMOVE_DOCUMENT_CATEGORY_REQUEST';
export const ADD_DOCUMENT_CATEGORY_REQUEST = 'ADD_DOCUMENT_CATEGORY_REQUEST';
